idle:
  color: [
    # white on the front, red on the back
    [0, 0, 0], # front left
    [0, 0, 0], # back right
    [0, 0, 0], # back left
    [0, 0, 0], # front right
    [1, 1, 1], # 
  ]
  intensity: [
    1.0,
    1.0,
    1.0,
    1.0,
    1.0
  ]
